"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple, Union

class CredentialProvider:
    """
    Credentials Provider.
    """
    def get_credentials(self) -> Union[Tuple[str], Tuple[str, str]]:
        ...
    


class UsernamePasswordCredentialProvider(CredentialProvider):
    """
    Simple implementation of CredentialProvider that just wraps static
    username and password.
    """
    def __init__(self, username: Optional[str] = ..., password: Optional[str] = ...) -> None:
        ...
    
    def get_credentials(self): # -> tuple[str, str] | tuple[str]:
        ...
    


