name: 'sobekwa'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris
    restart: unless-stopped
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
  api:
    build:
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=postgres    # We need to force the host value here.
      - API_SERVER_PORT=${API_SERVER_PORT}
      - JWT_AUTH_SECRET_KEY=${JWT_AUTH_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - AUTH_TOKEN_EXPIRE=${AUTH_TOKEN_EXPIRE}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:



  